"""empty message

Revision ID: 3130d70f0a5d
Revises: d8463450bfb8
Create Date: 2023-02-27 01:03:11.232086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3130d70f0a5d'
down_revision = 'd8463450bfb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_experience', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catch', schema=None) as batch_op:
        batch_op.drop_column('base_experience')

    # ### end Alembic commands ###
