"""empty message

Revision ID: 6f9dc9f64a28
Revises: ade62f497e42
Create Date: 2022-12-10 02:00:23.615556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9dc9f64a28'
down_revision = 'ade62f497e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('user_firstrname_key', type_='unique')
        batch_op.drop_constraint('user_lastname_key', type_='unique')
        batch_op.drop_column('firstrname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstrname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_lastname_key', ['lastname'])
        batch_op.create_unique_constraint('user_firstrname_key', ['firstrname'])
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###
