"""empty message

Revision ID: d8463450bfb8
Revises: 6f9dc9f64a28
Create Date: 2023-02-26 23:52:08.534930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8463450bfb8'
down_revision = '6f9dc9f64a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('abilities', sa.String(), nullable=False),
    sa.Column('base_stat', sa.String(), nullable=False),
    sa.Column('attack_base', sa.String(), nullable=False),
    sa.Column('defense_base', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catch')
    # ### end Alembic commands ###
